name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests
        run: mvn test

      - name: Generate HTML Report
        run: mvn site

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: junit-html-report
          path: target/site/surefire-report.html
